params:
  Decision Tree:
    criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson
    # splitter:
    #   - best
    #   - random
    # max_features:
    #   - sqrt
    #   - log2

  Random Forest:
    # criterion:
    #   - squared_error
    #   - friedman_mse
    #   - absolute_error
    #   - poisson
    # max_features:
    #   - sqrt
    #   - log2
    #   - null
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  Gradient Boosting:
    # loss:
    #   - squared_error
    #   - quantile
    #   - absolute_error
    #   - huber
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    subsample:
      - 0.6
      - 0.7
      - 0.75
      - 0.8
      - 0.85
      - 0.9
    # criterion:
    #   - squared_error
    #   - friedman_mse
    # max_features:
    #   - sqrt
    #   - log2
    #   - auto
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  Linear Regression: {}

  k-Neighbors Regression:
    n_estimators:
      - 5
      - 7
      - 9
      - 11
    # weights:
    #   - uniform
    #   - distance
    # algorithm:
    #   - ball_tree
    #   - kd_tree
    #   - brute

  XGBRegression:
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  CatBoosting Regression:
    depth:
      - 6
      - 8
      - 10
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    iterations:
      - 30
      - 50
      - 100

  AdaBoost Regression:
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    # loss:
    #   - linear
    #   - square
    #   - exponential
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
